[book]
title = "Zenoh Programming in Rust"
authors = ["Angelo Corsaro"]
description = "A practical guide to Eclipse Zenoh with Rust."
language = "en"
src = "src"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/kydos/zenoh-book"
