[book]
title = "Zenoh Programming in Rust (Draft)"
authors = ["Angelo Corsaro"]
description = "A practical guide to Eclipse Zenoh with Rust."
language = "en"
src = "src"

[rust]
edition = "2024"

[output.html]
additional-css = ["theme/draft.css"]
git-repository-url = "https://github.com/kydos/zenoh-book"
site-url = "/zenoh-book/"
